theme: jekyll-theme-tactile
name: Philip B. Graff
title: Welcome to Philip's homepage!
description: My personal website with code and discussion.
plugins:
  - jekyll-sitemap
#paginate: 5
#paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title
